name: CI

on:
  # push:
  #   tags:
  #     - "**" # match all tag names
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to create (optional)"
        required: false

# on:
#   push:
#     tags:
#       - "**" # match all tag names
#   pull_request:
#   workflow_dispatch:
#     inputs:
#       tag:
#         description: "The tag to create (optional)"
#         required: false

# concurrency:
#   group: arm-test-${{ github.ref }}
#   # Only cancel in progress if this is for a PR
#   cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ########################################################################
  ## Build Tagged Release
  ########################################################################
  build-source:
    # Only run if (a tag was passed in) -AND- (we're building the main branch which isn't a PR)
    if: ${{ github.event.inputs.tag != '' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    uses: wileyj/arm-test/.github/workflows/03-build-source.yml@master
    with:
      tag: ${{ github.event.inputs.tag }}
  github-release:
    # Only run if (a tag was passed in) -AND- (we're building the main branch which isn't a PR)
    if: ${{ github.event.inputs.tag != '' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    uses: wileyj/arm-test/.github/workflows/03-github-release.yml@master
    needs: build-source
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
  alpine-image:
    # Only run if (a tag was passed in) -AND- (we're building the main branch which isn't a PR)
    if: ${{ github.event.inputs.tag != '' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    uses: wileyj/arm-test/.github/workflows/03-alpine-image.yml@master
    needs: github-release
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  debian-image:
    # Only run if (a tag was passed in) -AND- (we're building the main branch which isn't a PR)
    if: ${{ github.event.inputs.tag != '' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    uses: wileyj/arm-test/.github/workflows/03-debian-image.yml@master
    needs: github-release
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  build-branch:
    # Only run if (a tag was NOT passed in) -OR- (we're building a non-master branch which isn't a PR)
    if: ${{ github.event.inputs.tag == '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: vals
        run: |
          echo "Build images from source"
          echo "github.event.inputs.tag: ${{ github.event.inputs.tag }}"
          echo "github.ref: ${{ github.ref }}"
          echo "branch: ${{ github.ref_name }}"
          echo "GITHUB_HEAD_REF: ${{ env.GITHUB_HEAD_REF }}"
          echo "GITHUB_BASE_REF: ${{ env.GITHUB_BASE_REF }}"
          echo "GITHUB_REF: ${{ env.GITHUB_REF }}"
          echo "GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}"
          echo "extracted: ${{ steps.extract_branch.outputs.branch }}"
  # build-branch:
  #   # Only run if (a tag was NOT passed in) or (we're building a non-master branch which isn't a PR)
  #   if: ${{ github.event.inputs.tag == '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
  #   uses: wileyj/arm-test/.github/workflows/02-build-branch.yml@master

# runs-on: ubuntu-latest
# steps:
#   - name: vals
#     run: |
#       echo "Build images from binaries"
#       echo "github.event.inputs.tag: ${{ github.event.inputs.tag }}"
#       echo "github.ref: ${{ github.ref }}"
