name: CI

on:
  push:
    # tags:
    #   - "**" # match all tag names
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to create (optional)"
        required: false

concurrency:
  group: arm-test-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ########################################################################
  ## Build Tagged Release
  ########################################################################
  build-source:
    # # if: ${{ github.event.inputs.tag != '' }}
    # if: ${{ (github.event.inputs.tag != '' || github.ref == 'refs/heads/master') && !contains(github.ref, 'refs/pull') }}
    # uses: wileyj/arm-test/.github/workflows/03-build-source.yml@master
    # with:
    #   tag: ${{ github.event.inputs.tag }}
    # secrets:
    #   GH_TOKEN: ${{ secrets.GH_TOKEN }}
    # if: ${{ !contains(github.ref, 'refs/pull') && (github.event.inputs.tag != '' && github.ref == 'refs/heads/master') }}
    # Only push if (a tag was passed in) or (we're building a non-master branch which isn't a PR)
    if: ${{ github.event.inputs.tag != '' || (github.ref != 'refs/heads/master' && !contains(github.ref, 'refs/pull')) }}
    runs-on: ubuntu-latest
    steps:
      - name: vals
        run: |
          echo "Build images from binaries"
          echo "github.event.inputs.tag: ${{ github.event.inputs.tag }}"
          echo "Tag was passed in -OR-"
          echo "  non-master branch which isn't a PR"
  build-branch:
    # if: ${{ contains(github.ref, 'refs/pull') || (github.event.inputs.tag == '' && github.ref != 'refs/heads/master') }}
    if: ${{ github.event.inputs.tag == '' && (github.ref != 'refs/heads/master' && !contains(github.ref, 'refs/pull')) }}
    runs-on: ubuntu-latest
    steps:
      - name: vals
        run: |
          echo "Build images from source"
          echo "github.event.inputs.tag: ${{ github.event.inputs.tag }}"
          echo "github.ref: ${{ github.ref }}"
          echo "Tag was not passed in -AND-"
          echo "  non-master branch which isn't a PR"

  # github-release:
  #   # if: ${{ github.event.inputs.tag != '' }}
  #   if: ${{ (github.event.inputs.tag != '' || github.ref == 'refs/heads/master') && !contains(github.ref, 'refs/pull') }}
  #   uses: wileyj/arm-test/.github/workflows/03-github-release.yml@master
  #   needs: build-source
  #   with:
  #     tag: ${{ github.event.inputs.tag }}
  #   secrets:
  #     GH_TOKEN: ${{ secrets.GH_TOKEN }}

  # alpine-image:
  #   # if: ${{ github.event.inputs.tag != '' }}
  #   if: ${{ (github.event.inputs.tag != '' || github.ref == 'refs/heads/master') && !contains(github.ref, 'refs/pull') }}
  #   uses: wileyj/arm-test/.github/workflows/03-alpine-image.yml@master
  #   needs: github-release
  #   with:
  #     tag: ${{ github.event.inputs.tag }}
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  # debian-image:
  #   # if: ${{ github.event.inputs.tag != '' }}
  #   if: ${{ github.event.inputs.tag != '' || (github.ref != 'refs/heads/master' && !contains(github.ref, 'refs/pull')) }}
  #   uses: wileyj/arm-test/.github/workflows/03-debian-image.yml@master
  #   needs: github-release
  #   with:
  #     tag: ${{ github.event.inputs.tag }}
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  #   ########################################################################
  #   ## Build Branch
  #   ########################################################################

#  build-branch:
#     # Only run if:
#     #   - a tag was not supplied
#     #   - building a non-master branch which isn't a PR
#     if: ${{ github.event.inputs.tag == '' && (github.ref != 'refs/heads/master' || !contains(github.ref, 'refs/pull')) }}
#     # startsWith(github.ref, 'refs/tags/')
#     uses: wileyj/arm-test/.github/workflows/02-build-branch.yml@master
#     secrets:
#       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#       DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
# # # The ref given is fully-formed, meaning that
# # # for branches the format images: refs/heads/<branch_name>
# # # for pull requests it is: refs/pull/<pr_number>/merge
# # # and for tags it is: refs/tags/<tag_name>
# # # For example, refs/heads/feature-branch-1.
