name: Build Debian Images

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
env:
  BUILD_PLATFORMS: linux/amd64, linux/amd64/v2, linux/amd64/v3
  # BUILD_PLATFORMS: linux/arm64, linux/amd64, linux/amd64/v2, linux/amd64/v3
  LINUX_VERSION: debian

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Vars
        if: ${{ github.event.inputs.tag != '' }}
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "GITHUB_REF_SHORT=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        if: ${{ github.event.inputs.tag != '' }}
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: ${{ github.event.inputs.tag != '' }}
        uses: docker/setup-buildx-action@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Docker meta
        if: ${{ github.event.inputs.tag != '' }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            wileyj/${{ github.event.repository.name }}
          tags: |
            type=raw,value=latest-${{ env.LINUX_VERSION }},enable=${{ github.event.inputs.tag != '' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) )}}
            type=raw,value=${{ github.event.inputs.tag }}-${{ env.LINUX_VERSION }},enable=${{ github.event.inputs.tag != '' }}
            type=raw,value=${{ steps.extract_branch.outputs.branch }}-${{ env.LINUX_VERSION }}
            type=ref,event=pr
      - name: Login to DockerHub
        if: ${{ github.event.inputs.tag != '' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Image
        if: ${{ github.event.inputs.tag != '' }}
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile.debian
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            TAG=${{ github.event.inputs.tag}}
            STACKS_NODE_VERSION=${{ github.event.inputs.tag || env.GITHUB_SHA_SHORT }}
            GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
            GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}
            BUILDKIT_PROGRESS=plain
          push: true
