name: Build AMD Images

# Only run when:
#   - PRs are opened against the master branch
#   - the workflow is started from the UI (an optional tag can be passed in via parameter)
#     - If the optional tag parameter is passed in, a new tag will be generated based off the selected branch
on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to create (optional)"
        required: false

concurrency:
  group: arm-test-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  BUILD_PLATFORMS: linux/amd64

jobs:
  # call the extra file to setup QEMU?
  call-docker-platforms-workflow:
    if: ${{ github.event.inputs.tag != '' }}
    uses: wileyj/arm-test/.github/workflows/docker-platforms.yml@master
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  # Build docker image, tag it with the git tag and `latest` if running on master branch, and publish under the following conditions
  # Will publish if:
  #   - a tag was passed into this workflow
  #   - a tag was pushed up
  #   - this workflow was invoked against a non-master branch (a Docker image tag with the name of the branch will be published)
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Vars notag
        # if: ${{ github.event.inputs.tag == '' }}
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "GITHUB_REF_SHORT=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Docker meta notag
        # if: ${{ github.event.inputs.tag == '' }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            wileyj/${{ github.event.repository.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=${{ github.event.inputs.tag }}

      - name: Set up Docker Buildx notag
        # if: ${{ github.event.inputs.tag == '' }}
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ env.BUILD_PLATFORMS }} Image
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/${{ github.event.repository.name }}.tar

      - name: Upload ${{ env.BUILD_PLATFORMS }} artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: /tmp/${{ github.event.repository.name }}.tar

      # - name: Build/Tag/Push Image notag
      #   # if: ${{ github.event.inputs.tag == '' }}
      #   uses: docker/build-push-action@v3
      #   with:
      #     platforms: ${{ env.BUILD_PLATFORMS }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     build-args: |
      #       STACKS_NODE_VERSION=${{ github.event.inputs.tag || env.GITHUB_SHA_SHORT }}
      #       GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
      #       GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}
      #     push: true
      #     # push: ${{ github.event.inputs.tag != '' || (github.ref != 'refs/heads/master' && !contains(github.ref, 'refs/pull')) }}
