name: Build AMD Images

on:
  workflow_call:

concurrency:
  group: arm-test-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  BUILD_PLATFORMS: linux/amd64
  OS_ARCH: amd64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Vars ${{ env.OS_ARCH }}
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "GITHUB_REF_SHORT=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Docker meta ${{ env.OS_ARCH }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            wileyj/${{ github.event.repository.name }}
          tags: |
            type=raw,value=${{ env.OS_ARCH }}

      - name: Set up Docker Buildx ${{ env.OS_ARCH }}
        uses: docker/setup-buildx-action@v2

      - name: Build Image ${{ env.OS_ARCH }}
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/${{ github.event.repository.name }}-${{ env.OS_ARCH }}.tar
          push: true

      - name: Upload artifact ${{ env.OS_ARCH }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: /tmp/${{ github.event.repository.name }}-${{ env.OS_ARCH }}.tar

      # - name: Create tag manifest
      #   if: ${{ github.event.inputs.tag != '' }}
      #   run: |
      #     docker manifest create wileyj/${{ github.event.repository.name }}:${{ github.event.inputs.tag }} \
      #     --amend wileyj/${{ github.event.repository.name }}:amd64
      #     docker manifest inspect wileyj/${{ github.event.repository.name }}:${{ github.event.inputs.tag }}

      # - name: Create branch manifest
      #   run: |
      #     docker manifest create wileyj/${{ github.event.repository.name }}:${{ env.GITHUB_REF_SHORT }} \
      #     --amend wileyj/${{ github.event.repository.name }}:amd64
      #     docker manifest inspect wileyj/${{ github.event.repository.name }}:${{ env.GITHUB_REF_SHORT }}
