name: Build ARM Images

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

env:
  BUILD_PLATFORMS: linux/arm64
  OS_ARCH: arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Vars ${{ env.OS_ARCH }}
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "GITHUB_REF_SHORT=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU ${{ env.OS_ARCH }}
        uses: docker/setup-qemu-action@v2

      - name: Docker meta ${{ env.OS_ARCH }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            wileyj/${{ github.event.repository.name }}
          tags: |
            type=raw,value=${{ env.OS_ARCH }}

      - name: Set up Docker Buildx ${{ env.OS_ARCH }}
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ env.OS_ARCH }} Image
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/${{ github.event.repository.name }}-${{ env.OS_ARCH }}.tar

      - name: Upload artifact ${{ env.OS_ARCH }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: /tmp/${{ github.event.repository.name }}-${{ env.OS_ARCH }}.tar

      - name: Create tag manifest
        if: ${{ github.event.inputs.tag == '' }}
        run: |
          docker manifest create wileyj/${{ github.event.repository.name }}:${{ github.event.inputs.tag }} \
          --amend wileyj/${{ github.event.repository.name }}:arm64
          docker manifest inspect wileyj/${{ github.event.repository.name }}:${{ github.event.inputs.tag }}

      - name: Create branch manifest
        run: |
          docker manifest create wileyj/${{ github.event.repository.name }}:${{ env.GITHUB_REF_SHORT }} \
          --amend wileyj/${{ github.event.repository.name }}:arm64
          docker manifest inspect wileyj/${{ github.event.repository.name }}:${{ env.GITHUB_REF_SHORT }}
