name: Security Audit

on:
  # push:
  #   paths:
  #     - "**/Cargo.toml"
  #     - "**/Cargo.lock"
  pull_request:
  workflow_call:
  # schedule:
  #   - cron: "30 15 * * *" # UTC

jobs:
  leaked-cred-test:
    name: Leaked Credential Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # extract branch name NOT a pull request
      - name: Extract branch name
        if: ${{ github.event_name != 'pull_request' }}
        id: extract_branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      # extract branch name on pull request
      - name: PR branch name
        if: ${{ github.event_name == 'pull_request' }}
        id: pr_extract_branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.4.3
        with:
          path: ./
          base: ${{ env.BRANCH_NAME }}
          head: HEAD

  security_audit:
    name: Crate Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # # check for cve's in rust deps
      - name: Rust Dep Check
        id: rust_dep_check
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
