name: Security Audit
on:
  workflow_dispatch:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: 30 03 * * *

jobs:
  leaked-cred-test:
    name: Leaked Credential Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.4.3
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

  security_audit:
    name: Crate Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Rust Dep Check
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
