name: Build Source Debian

on:
  workflow_call:
    inputs:
      platforms:
        required: true
        description: "Arch to buid debian images"
        type: string
        # default: linux/amd64, linux/amd64/v2, linux/amd64/v3
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
env:
  LINUX_VERSION: debian

concurrency:
  group: arm-test-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Vars
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "GITHUB_REF_SHORT=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # extract branch name NOT a pull request
      - name: Extract branch name
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        id: extract_branch

      # extract branch name on pull request
      - name: PR branch name
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            wileyj/${{ github.event.repository.name }}
          tags: |
            type=raw,value=${{ env.BRANCH_NAME }}-${{ env.LINUX_VERSION }}
            type=ref,event=pr

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Workflow Values
        run: |
          echo "Docker Debian-source Vals"
          echo "inputs.platform: ${{ inputs.platforms }}"
          echo "inputs.tag: ${{ inputs.tag }}"
          echo "LINUX_VERSION: ${{ env.LINUX_VERSION }}"
          echo "github.ref: ${{ github.ref }}"
          echo "branch: ${{ github.ref_name }}"
          echo "GITHUB_HEAD_REF: ${{ env.GITHUB_HEAD_REF }}"
          echo "GITHUB_BASE_REF: ${{ env.GITHUB_BASE_REF }}"
          echo "GITHUB_REF: ${{ env.GITHUB_REF }}"
          echo "GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}"
          echo "extracted: ${{ steps.extract_branch.outputs.branch }}"
          echo "Branch Name: ${{ env.BRANCH_NAME }}"

      - name: Build/Tag/Push Image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.debian-source
          platforms: ${{ inputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            STACKS_NODE_VERSION=${{ env.GITHUB_SHA_SHORT }}
            GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
            GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}
          push: true
