name: Build Distributable Assets

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      platforms:
        description: "Stringified JSON object listing of platform matrix"
        required: true
        type: string
jobs:
  asset:
    if: ${{ github.event.inputs.tag != '' }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: ${{fromJson(inputs.platforms)}}
      # matrix:
      #   platform:
      #     - linux-glibc-x64
      #     - linux-musl-x64
      #     # - linux-glibc-arm64
      #     # - linux-musl-arm64
      #     # - macos-x64
      #     # - macos-arm64
      #     # - windows-x64

    steps:
      - uses: actions/checkout@v2
      - name: Set Vars
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "GITHUB_REF_SHORT=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Binaries
        id: build_binaries
        uses: docker/build-push-action@v3
        with:
          file: build-scripts/Dockerfile.${{ matrix.platform }}
          outputs: type=local,dest=./dist/${{ matrix.platform }}
          build-args: |
            OS_ARCH=${{ matrix.platform }}
            GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
            GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}

      - name: Compress artifact
        id: compress_artifact
        run: zip --junk-paths ${{ matrix.platform }} ./dist/${{ matrix.platform }}/*

      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.platform }}.zip
