name: Build Distributable Assets

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
jobs:
  asset:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        platform:
          - linux-glibc-x64
          - linux-musl-x64
          # - linux-glibc-arm64
          # - linux-musl-arm64
          # - macos-x64
          # - macos-arm64
          # - windows-x64

    steps:
      - uses: actions/checkout@v2
      - name: Set Vars
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "GITHUB_REF_SHORT=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Binaries
        id: build_binaries
        uses: docker/build-push-action@v3
        with:
          file: build-scripts/Dockerfile.${{ matrix.platform }}
          outputs: type=local,dest=./dist/${{ matrix.platform }}
          build-args: |
            OS_ARCH=${{ matrix.platform }}
            GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
            GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}

      - name: Compress artifact
        id: compress_artifact
        run: zip --junk-paths ${{ matrix.platform }} ./dist/${{ matrix.platform }}/*

      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}.zip
          path: ${{ matrix.platform }}.zip

      # - name: artifact checksum
      #   id: artifact_checksum
      #   uses: tristan-weil/ghaction-checksum-sign-artifact@v1
      #   with:
      #     checksum_format: gnu
      #     checksum_output: one_file
      #     path: ${{ matrix.platform }}.zip
      #     # checksum_output: artifact_one_file_per_digest
      # - name: Upload checksum
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ matrix.platform }}
      #     path: ${{ matrix.platform }}.zip.sha256
      #
      #
      #
      #

      # - name: Upload checksum
      #   id: upload_checksum
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ steps.artifact_checksum.outputs.generated-files }}
      #     path: ${{ steps.artifact_checksum.outputs.generated-files }}
