name: Build Debian Source Image

on:
  workflow_call:
    inputs:
      docker_platforms:
        required: true
        description: "Arch to buid debian images"
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
env:
  LINUX_VERSION: debian

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Vars
        id: set_vars
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "GITHUB_REF_SHORT=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      # extract branch name NOT a pull request
      - name: Extract branch name
        if: ${{ github.event_name != 'pull_request' }}
        id: extract_branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      # extract branch name on pull request
      - name: PR branch name
        if: ${{ github.event_name == 'pull_request' }}
        id: pr_extract_branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV

      - name: Docker Metadata
        id: docker_metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            wileyj/${{ github.event.repository.name }}
          tags: |
            type=raw,value=${{ env.BRANCH_NAME }}-${{ env.LINUX_VERSION }}
            type=ref,event=pr

      - name: Login to DockerHub
        id: docker_login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: ./.github/actions/dockerhub/Dockerfile.debian-source
          platforms: ${{ inputs.docker_platforms }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          build-args: |
            STACKS_NODE_VERSION=${{ env.GITHUB_SHA_SHORT }}
            GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
            GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}
          push: true
