name: CI

on:
  # push:
  #   tags:
  #     - "**" # match all tag names
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to create (optional)"
        required: false

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ########################################################################
  ## Build Tagged Release
  ########################################################################
  build-source:
    # Only run if (a tag was passed in) -AND- (we're building the main branch which isn't a PR)
    # Note: build matrix is defined in ./build-source-binary.yml (it is not reusable)
    if: ${{ inputs.tag != '' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    uses: wileyj/arm-test/.github/workflows/build-source-binary.yml@master
    with:
      tag: ${{ inputs.tag }}
      platforms: >-
        ["linux-glibc-x64", linux-musl-x64"]

  github-release:
    # Only run if (a tag was passed in) -AND- (we're building the main branch which isn't a PR)
    if: ${{ inputs.tag != '' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    uses: wileyj/arm-test/.github/workflows/github-release.yml@master
    needs: build-source
    with:
      tag: ${{ inputs.tag }}
      platforms: >-
        ["linux-glibc-x64", linux-musl-x64"]
      # platforms: >-
      #   ["linux-glibc-x64", linux-musl-x64", "linux-glibc-arm64", "linux-musl-arm64", "macos-x64", "macos-arm64", "windows-x64"]
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  # docker-alpine:
  #   # Only run if (a tag was passed in) -AND- (we're building the main branch which isn't a PR)
  #   if: ${{ inputs.tag != '' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
  #   uses: wileyj/arm-test/.github/workflows/image-build-alpine.yml@master
  #   needs: github-release
  #   with:
  #     tag: ${{ inputs.tag }}
  #     platforms: linux/arm64, linux/amd64, linux/amd64/v2, linux/amd64/v3
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  # docker-debian:
  #   # Only run if (a tag was passed in) -AND- (we're building the main branch which isn't a PR)
  #   if: ${{ inputs.tag != '' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
  #   uses: wileyj/arm-test/.github/workflows/image-build-debian.yml@master
  #   needs: github-release
  #   with:
  #     tag: ${{ inputs.tag }}
  #     platforms: linux/amd64, linux/amd64/v2, linux/amd64/v3
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  # ########################################################################
  # ## Build Branch/PR
  # ########################################################################
  # build-branch:
  #   # Only run if (a tag was NOT passed in) or (we're building a non-master branch which isn't a PR)
  #   if: ${{ inputs.tag == '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
  #   uses: wileyj/arm-test/.github/workflows/build-source-image.yml@master
  #   with:
  #     platforms: linux/amd64, linux/amd64/v2, linux/amd64/v3
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
