name: CI

on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to create (optional)"
        required: false

env:
  BUILD_PLATFORMS: linux/amd64, linux/arm64

jobs:
  amd64:
    uses: wileyj/arm-test/.github/workflows/amd.yml@master

  # call the extra file to setup QEMU?
  arm64:
    if: ${{ github.event.inputs.tag != '' }}
    uses: wileyj/arm-test/.github/workflows/arm.yml@master
    with:
      tag: ${{ github.event.inputs.tag }}

  build:
    runs-on: ubuntu-latest
    needs: amd64 # amd64 being the default arch, require it
    steps:
      - uses: actions/checkout@v2

      - name: Set Vars
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "GITHUB_REF_SHORT=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: /tmp

      - name: Load AMD Image
        run: |
          docker load --input /tmp/${{ github.event.repository.name }}-amd64.tar
          docker image ls

      - name: Load ARM Image
        if: ${{ github.event.inputs.tag != '' }}
        run: |
          docker load --input /tmp/${{ github.event.repository.name }}-arm64.tar
          docker image ls

      - name: List images
        run: |
          docker image ls

      # - name: List Tag Manifest
      #   if: ${{ github.event.inputs.tag != '' }}
      #   run: |
      #     docker manifest inspect wileyj/${{ github.event.repository.name }}:${{ github.event.inputs.tag }}

      # - name: List Branch Manifest
      #   run: |
      #     docker manifest inspect wileyj/${{ github.event.repository.name }}:${{ env.GITHUB_REF_SHORT }}

      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Build and push branch
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     platforms: ${{ env.BUILD_PLATFORMS }}
      #     push: true
      #     tags: wileyj/${{ github.event.repository.name }}:${{ env.GITHUB_REF_SHORT }}

      # - name: Build and push tag
      #   if: ${{ github.event.inputs.tag != '' }}
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     platforms: ${{ env.BUILD_PLATFORMS }}
      #     push: true
      #     tags: wileyj/${{ github.event.repository.name }}:${{ github.event.inputs.tag }}
