name: CI

on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to create (optional)"
        required: false

concurrency:
  group: arm-test-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-assets:
    if: ${{ github.event.inputs.tag != '' }}
    uses: wileyj/arm-test/.github/workflows/build-assets.yml@master
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  gh-release:
    if: ${{ github.event.inputs.tag != '' }}
    uses: wileyj/arm-test/.github/workflows/gh-release.yml@master
    needs: build-assets
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-alpine:
    if: ${{ github.event.inputs.tag != '' }}
    uses: wileyj/arm-test/.github/workflows/build-alpine.yml@master
    needs: gh-release
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  build-debian:
    if: ${{ github.event.inputs.tag != '' }}
    uses: wileyj/arm-test/.github/workflows/build-debian.yml@master
    needs: gh-release
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
