name: CI

on:
  # push:
  #   tags:
  #     - "**" # match all tag names
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to create (optional)"
        required: false

env:
  build_platforms: linux/arm64, linux/amd64, linux/amd64/v2, linux/amd64/v3 # for release, build amd *and* most recent arm64 arch
  debian_platforms: linux/amd64, linux/amd64/v2, linux/amd64/v3 # only amd arch is supported for branch/pr builds

concurrency:
  group: arm-test-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ########################################################################
  ## Build Tagged Release
  ########################################################################
  build-source:
    # Only run if (a tag was passed in) -AND- (we're building the main branch which isn't a PR)
    # Note: build matrix is defined in ./build-source-binary.yml (it is not reusable)
    if: ${{ github.event.inputs.tag != '' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    uses: wileyj/arm-test/.github/workflows/build-source-binary.yml@master
    with:
      tag: ${{ github.event.inputs.tag }}

  github-release:
    # Only run if (a tag was passed in) -AND- (we're building the main branch which isn't a PR)
    if: ${{ github.event.inputs.tag != '' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    uses: wileyj/arm-test/.github/workflows/github-release.yml@master
    needs: build-source
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  docker-alpine:
    # Only run if (a tag was passed in) -AND- (we're building the main branch which isn't a PR)
    if: ${{ github.event.inputs.tag != '' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    uses: wileyj/arm-test/.github/workflows/image-build-alpine.yml@master
    needs: github-release
    with:
      tag: ${{ github.event.inputs.tag }}
      build_platforms: ${{ github.env.build_platforms }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  docker-debian:
    # Only run if (a tag was passed in) -AND- (we're building the main branch which isn't a PR)
    if: ${{ github.event.inputs.tag != '' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    uses: wileyj/arm-test/.github/workflows/image-build-debian.yml@master
    needs: github-release
    with:
      tag: ${{ github.event.inputs.tag }}
      build_platforms: ${{ github.env.debian_platforms }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  ########################################################################
  ## Build Branch/PR
  ########################################################################
  build-branch:
    # Only run if (a tag was NOT passed in) or (we're building a non-master branch which isn't a PR)
    if: ${{ github.event.inputs.tag == '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
    uses: wileyj/arm-test/.github/workflows/build-source-image.yml@master
    with:
      build_platforms: ${{ github.env.debian_platforms }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  # build-branch:
  #   # Only run if (a tag was NOT passed in) -OR- (we're building a non-master branch which isn't a PR)
  #   if: ${{ github.event.inputs.tag == '' || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && !contains(github.ref, 'refs/pull')) }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     # extract branch name NOT a pull request
  #     - name: Extract branch name
  #       if: ${{ github.event_name != 'pull_request' }}
  #       run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
  #       id: extract_branch
  #
  #     # extract branch name on pull request
  #     - name: PR branch name
  #       if: ${{ github.event_name == 'pull_request' }}
  #       run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
  #
  #     - name: vals
  #       run: |
  #         echo "Build images from source"
  #         echo "github.event.inputs.tag: ${{ github.event.inputs.tag }}"
  #         echo "github.ref: ${{ github.ref }}"
  #         echo "branch: ${{ github.ref_name }}"
  #         echo "GITHUB_HEAD_REF: ${{ env.GITHUB_HEAD_REF }}"
  #         echo "GITHUB_BASE_REF: ${{ env.GITHUB_BASE_REF }}"
  #         echo "GITHUB_REF: ${{ env.GITHUB_REF }}"
  #         echo "GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}"
  #         echo "extracted: ${{ steps.extract_branch.outputs.branch }}"
  #         echo "Branch Name: ${{ env.BRANCH_NAME }}"
