name: CI

on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to create (optional)"
        required: false

env:
  BUILD_PLATFORMS: linux/amd64, linux/arm64, linux/arm/v7

jobs:
  build-amd:
    uses: wileyj/arm-test/.github/workflows/amd.yml@master

  # call the extra file to setup QEMU?
  build-arm:
    if: ${{ github.event.inputs.tag != '' }}
    uses: wileyj/arm-test/.github/workflows/arm.yml@master
    with:
      tag: ${{ github.event.inputs.tag }}

  build:
    runs-on: ubuntu-latest
    needs: build-amd
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/${{ github.event.repository.name }}.tar
          docker image ls -a

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
