# https://github.com/actions-rs/grcov

# https://github.com/actions-rs/cargo

name: Local Tests

on:
  workflow_dispatch:

env:
  RUSTFLAGS: "-Cinstrument-coverage"
  LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"

jobs:
  full-genesis:
    # env:
    #   RUSTFLAGS: "-Cinstrument-coverage"
    #   LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"
    name: Full Genesis Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3

      - name: Setup Rust Toolchain
        id: rust_toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools-preview

      # - name: Install nextest
      #   uses: baptiste0928/cargo-install@v2
      #   with:
      #     crate: nextest
      - name: Install nextest
        id: install_nextest
        run: |
          curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Nextest
        id: cargo_nextest
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"
        with:
          command: nextest run
          args: --workspace

      # - name: Cargo Build
      #   id: cargo_build
      #   uses: actions-rs/cargo@v1
      #   env:
      #     RUSTFLAGS: "-Cinstrument-coverage"
      #     LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"
      #   with:
      #     command: build
      #     args: --workspace
