# https://github.com/actions-rs/grcov

# https://github.com/actions-rs/cargo

name: Local Tests

on:
  workflow_dispatch:

env:
  RUSTFLAGS: "-Cinstrument-coverage"
  LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"

jobs:
  full-genesis:
    env:
      RUSTFLAGS: "-Cinstrument-coverage"
      LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"
    name: Full Genesis Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        id: setup_rust_toolchain
        with:
          toolchain: stable
          components: llvm-tools-preview

      - name: Install Nextest
        id: install_nextest
        run: |
          curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Install grcov
        id: install_grcov
        run: |
          VERSION=$(curl -sL https://api.github.com/repos/mozilla/grcov/releases/latest | jq -r .tag_name)
          ARCH=x86_64
          LIBC=gnu
          PLATFORM=unknown-linux
          curl -LsSf "https://github.com/mozilla/grcov/releases/download/${VERSION}/grcov-${ARCH}-${PLATFORM}-${LIBC}.tar.bz2" | tar jxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Run Tests
        id: run_tests
        run: |
          cargo nextest run --workspace --no-fail-fast --all-targets --tests --release --test-threads 8 --build-jobs 8

      - name: Run grcov
        id: run_grcov
        run: |
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info

      # - name: Unit Test Codecov
      #   id: codedov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: ./lcov.info
      #     name: unit_tests
      #     fail_ci_if_error: true

  open-api-validation:
    name: OpenAPI Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3

      # use the public name of the action
      - name: redoc-cli test
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: "bundle -o ./open-api-docs.html ./docs/rpc/openapi.yaml"

      - name: check result
        run: |
          ls -al
          test -f ./open-api-docs.html || (echo "Missing ./open-api-docs.html from previous step." && exit 1)

      # - uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./lcov.info
