# https://github.com/actions-rs/grcov

# https://github.com/actions-rs/cargo

name: Local Tests

on:
  workflow_dispatch:

env:
  RUSTFLAGS: "-Cinstrument-coverage"
  LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"

jobs:
  full-genesis:
    # env:
    #   RUSTFLAGS: "-Cinstrument-coverage"
    #   LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"
    name: Full Genesis Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3

      - name: Setup Rust Toolchain
        id: rust_toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools-preview

      - uses: SierraSoftworks/setup-grcov@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: latest

      - name: Run tests
        id: nextest
        env:
          RUSTFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"
        run: |
          curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
          cargo nextest run --workspace

      # - name: Nextest
      #   id: run_nextest
      #   env:
      #     RUSTFLAGS: "-Cinstrument-coverage"
      #     LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"
      #   run: cargo nextest run --workspace

      - name: grcov
        id: grcov
        run: |
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
          ls -al lcov.info
      # - uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./lcov.info

      # - name: Cargo Build
      #   id: cargo_build
      #   uses: actions-rs/cargo@v1
      #   env:
      #     RUSTFLAGS: "-Cinstrument-coverage"
      #     LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"
      #   with:
      #     command: build
      #     args: --workspace
