# https://github.com/actions-rs/grcov

# https://github.com/actions-rs/cargo

name: Local Bitcoin Tests

on:
  workflow_dispatch:

env:
  BTC_VERSION: "0.20.0"

jobs:
  sampled-genesis:
    name: Sampled Genesis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        id: setup_rust_toolchain
        with:
          toolchain: stable
          components: llvm-tools-preview

      - name: Install Bitcoin Binary
        id: bitcoin_binary
        run: |
          curl -LSf https://bitcoin.org/bin/bitcoin-core-${BTC_VERSION}/bitcoin-${BTC_VERSION}-x86_64-linux-gnu.tar.gz | tar zxf - -C /tmp
          ln -s /tmp/bitcoin-${BTC_VERSION}/bin/bitcoind /bin/

      - name: ls
        run: |
          ls -al /tmp
          ls -al /bin/bitcoind

      - name: Install grcov
        id: install_grcov
        uses: SierraSoftworks/setup-grcov@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: latest

      - name: Run tests
        id: run_tests
        env:
          RUSTFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "stacks-blockchain-%p-%m.profraw"
        run: |
          curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
          cargo nextest run --workspace  --no-fail-fast --all-targets --tests --release --build-jobs 8 --test-threads 8

      - name: Run grcov
        id: run_grcov
        run: |
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info

      # - uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./lcov.info
