name: CI

on:
  push:
    # tags:
    #   - "**" # match all tag names
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to create (optional)"
        required: false

concurrency:
  group: arm-test-${{ github.ref }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-docker:
    # Only run if:
    #   - a tag was supplied
    #   - building a master branch which isn't a PR
    if: ${{ github.event.inputs.tag != '' && (github.ref == 'refs/heads/master' && !contains(github.ref, 'refs/pull')) }}
    # startsWith(github.ref, 'refs/tags/')
    uses: wileyj/arm-test/.github/workflows/tag-release/main.yml@master
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  build-branch:
    # Only run if:
    #   - a tag was not supplied
    #   - building a non-master branch which isn't a PR
    if: ${{ github.event.inputs.tag == '' && (github.ref != 'refs/heads/master' || !contains(github.ref, 'refs/pull')) }}
    # startsWith(github.ref, 'refs/tags/')
    uses: wileyj/arm-test/.github/workflows/branch-release/main.yml@master
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
# The ref given is fully-formed, meaning that
# for branches the format images: refs/heads/<branch_name>
# for pull requests it is: refs/pull/<pr_number>/merge
# and for tags it is: refs/tags/<tag_name>
# For example, refs/heads/feature-branch-1.

